import Foundation

struct SettingsDefaultsState {
    var refreshFrequency: RefreshFrequency
    var appLanguageRaw: String?
    var launchAtLogin: Bool
    var debugMenuEnabled: Bool
    var debugDisableKeychainAccess: Bool
    var debugFileLoggingEnabled: Bool
    var debugLogLevelRaw: String?
    var debugLoadingPatternRaw: String?
    var debugKeepCLISessionsAlive: Bool
    var statusChecksEnabled: Bool
    var loginNotificationsEnabled: Bool
    var augmentSessionExpiredNotificationsEnabled: Bool
    var sessionQuotaNotificationsEnabled: Bool
    var sessionQuotaThresholdNotificationsEnabled: Bool
    var sessionQuotaUsageThresholdsRaw: [Int]
    var weeklyLimitThresholdNotificationsEnabled: Bool
    var weeklyLimitRecoveryNotificationsEnabled: Bool
    var weeklyLimitUsageThresholdsRaw: [Int]
    var usageBarsShowUsed: Bool
    var resetTimesShowAbsolute: Bool
    var resetTimeDisplayStyleRaw: String?
    var menuBarShowsBrandIconWithPercent: Bool
    var menuBarUsageDisplayStyleRaw: String?
    var menuBarDisplayModeRaw: String?
    var historicalTrackingEnabled: Bool
    var showAllTokenAccountsInMenu: Bool
    var menuBarMetricPreferencesRaw: [String: String]
    var costUsageEnabled: Bool
    var hidePersonalInfo: Bool
    var randomBlinkEnabled: Bool
    var confettiOnWeeklyLimitResetsEnabled: Bool
    var menuBarShowsHighestUsage: Bool
    var claudeOAuthKeychainPromptModeRaw: String?
    var claudeOAuthKeychainReadStrategyRaw: String?
    var claudeWebExtrasEnabledRaw: Bool
    var claudePeakHoursEnabled: Bool
    var showOptionalCreditsAndExtraUsage: Bool
    var openAIWebAccessEnabled: Bool
    var openAIWebBatterySaverEnabled: Bool
    var providerStorageFootprintsEnabled: Bool
    var jetbrainsIDEBasePath: String
    var mergeIcons: Bool
    var switcherShowsIcons: Bool
    var mergedMenuLastSelectedWasOverview: Bool
    var mergedOverviewSelectedProvidersRaw: [String]
    var selectedMenuProviderRaw: String?
    var providerDetectionCompleted: Bool
}
